<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 7" host="RD-ZHANGYANG"><DocLocation><![CDATA[F:\QTP_10.X\QTP_EC10_预研\清理环境_启动EC10进程_001]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[清理环境_启动EC10进程_001]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="45" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[Output to global sheet]]></Obj>
<Details ><![CDATA[Name: 启动文件路径
Value: "C:\Program Files (x86)\EC 10.0\Bin\EC.exe"]]></Details>
<Time><![CDATA[2018/3/23 - 15:32:34]]></Time>
<TimeTick>1521790354</TimeTick>
<NodeArgs eType="User" icon="46" nRep="6" status="Information" >
<Disp><![CDATA[Output to global sheet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T4">
<Obj ><![CDATA[This test is run in the EC-QA  environment by zhangyang on RD-ZHANGYANG]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[2018/3/23 - 15:32:34]]></Time>
<TimeTick>1521790354</TimeTick>
<NodeArgs eType="User" icon="46" nRep="7" status="Information" >
<Disp><![CDATA[This test is run in the EC-QA  environment by zhangyang on RD-ZHANGYANG]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T5" iterID="1" >
<Action rID="T6">
<AName><![CDATA[Action1]]></AName>
<Action rID="T7">
<AName><![CDATA[Action1 [清理_启动]]]></AName>
<Step rID="T8">
<Obj ><![CDATA[Action Run: 清理所有EC进程]]></Obj>
<Details ><![CDATA[Data Row: 1]]></Details>
<Time><![CDATA[2018/3/23 - 15:32:35]]></Time>
<TimeTick>1521790355</TimeTick>
<NodeArgs eType="User" icon="46" nRep="11" status="Information" >
<Disp><![CDATA[Action Run: 清理所有EC进程]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/3/23 - 15:32:35" eTime="2018/3/23 - 15:32:46" passed="0" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[清理所有EC进程]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="49" nRep="10" >
<Disp><![CDATA[Action1 [清理_启动] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T9">
<AName><![CDATA[Action1 [清理_启动]]]></AName>
<Step rID="T10">
<Obj ><![CDATA[Action Run: 启动EC]]></Obj>
<Details ><![CDATA[Data Row: 2]]></Details>
<Time><![CDATA[2018/3/23 - 15:32:47]]></Time>
<TimeTick>1521790367</TimeTick>
<NodeArgs eType="User" icon="46" nRep="14" status="Information" >
<Disp><![CDATA[Action Run: 启动EC]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2018/3/23 - 15:32:48]]></Time>
<TimeTick>1521790368</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\EC 10.0\Bin\EC.exe"",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\EC 10.0\Bin\EC.exe"",1]]></Details>
<Time><![CDATA[2018/3/23 - 15:32:48]]></Time>
<TimeTick>1521790368</TimeTick>
<NodeArgs eType="Replay" icon="50" nRep="18" status="Passed" Source="Action1 [清理_启动]" SourceLine="-1" >
<Disp><![CDATA[Run ""C:\Program Files (x86)\EC 10.0\Bin\EC.exe"",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="50" nRep="17" status="Passed" Source="Action1 [清理_启动]" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[EC10.0]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2018/3/23 - 15:32:49]]></Time>
<TimeTick>1521790369</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[登录按钮.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2018/3/23 - 15:32:49]]></Time>
<TimeTick>1521790369</TimeTick>
<NodeArgs eType="Replay" icon="52" nRep="20" Source="Action1 [清理_启动]" SourceLine="-1" >
<Disp><![CDATA[登录按钮.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="51" nRep="19" Source="Action1 [清理_启动]" SourceLine="-1" >
<Disp><![CDATA[EC10.0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[启动是否成功]]></Obj>
<Details ><![CDATA[启动成功！]]></Details>
<Time><![CDATA[2018/3/23 - 15:32:49]]></Time>
<TimeTick>1521790369</TimeTick>
<NodeArgs eType="User" icon="46" nRep="21" status="Passed" Source="Action1 [清理_启动]" SourceLine="-1" >
<Disp><![CDATA[启动是否成功]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018/3/23 - 15:32:47" eTime="2018/3/23 - 15:32:49" passed="2" failed="0" warnings="0" ><Param ><ParamName><![CDATA[Action]]></ParamName><ParamVal><![CDATA[启动EC]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="49" nRep="13" status="Passed" >
<Disp><![CDATA[Action1 [清理_启动] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2018/3/23 - 15:32:34" eTime="2018/3/23 - 15:32:50" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="48" nRep="9" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="47" nRep="8" status="Passed" >
<Disp><![CDATA[清理环境_启动EC10进程_001 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2018/3/23 - 15:32:33" eTime="2018/3/23 - 15:32:50" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="44" nRep="3" status="Passed" >
<Disp><![CDATA[Test 清理环境_启动EC10进程_001 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>